yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from .constants import FIRST_15_LETTERS

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        null=True,
        blank=True
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:FIRST_15_LETTERS]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField('Текст', help_text='Текст нового комментария')
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following')

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].required = True

    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        help_texts = {
            'text': ('Текст нового поста'),
            'group': ('Группа, к которой будет относиться пост'),
            'image': ('Картинка для поста')
        }
        labels = {
            'text': 'Текст поста',
            'group': 'Группа '
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.urls import reverse
from .utils.paginate import paginate
from .models import Group, Post, Follow
from .forms import PostForm, CommentForm

User = get_user_model()


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    page_obj = paginate(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginate(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = User.objects.get(username=username)
    posts = Post.objects.filter(author=author)
    page_obj = paginate(request, posts)
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': False
    }
    if request.user.is_authenticated:
        context['following'] = Follow.objects.filter(
            user=request.user).filter(author=author).exists()
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': CommentForm(),
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    template = 'posts/create_post.html'
    if not form.is_valid():
        return render(request, template, {'form': form})
    else:
        user = get_object_or_404(User, username=request.user.username)
        post = form.save(commit=False)
        post.text = form.cleaned_data['text']
        post.author = user
        post.group = form.cleaned_data['group']
        post.save()
        return redirect('posts:profile', username=user.username)


def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = get_object_or_404(User, id=request.user.id)
    authors = user.follower.all()
    posts = Post.objects.filter(author__following__in=authors)
    page_obj = paginate(request, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author)
    return redirect(reverse('posts:profile',
                            kwargs={'username': username}))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    get_object_or_404(Follow,
                      user=request.user,
                      author=author).delete()
    return redirect(reverse('posts:profile',
                            kwargs={'username': username}))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}Новый пост{% endblock title %}
{% load user_filters %}

{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
                {% if is_edit %}
                  <div class="card-header">
                    Редактировать пост
                  </div>
                {% else %}
                  <div class="card-header">
                    Новый пост
                  </div>
                {% endif %}
              <div class="card-body">
                <form method="post" action="{% if is_edit %}{% url 'posts:post_edit' post.id %}{% else %}{% url 'posts:post_create' %}{% endif %}" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ form.text.id_for_label }}">
                        {{ form.text.label }}
                        {% if form.text.field.required %}
                            <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ form.text|addclass:"form-control" }}
                    <small id="id_text-help" class="form-text text-muted">
                      {{ form.text.help_text }}
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="{{ form.group.id_for_label }}">
                        {{ form.group.label }}
                        {% if field.field.required %}
                            <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ form.group|addclass:"form-control" }}
                    <small id="id_group-help" class="form-text text-muted">
                      {{ form.group.help_text }}
                    </small>
                  </div>
                    {{form.image}}

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock title %}
{% load thumbnail %}
{% load cache %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <main>
    <div class="container py-5">
      <h1>Избранные авторы</h1>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                    Автор: {% if not post.author.first_name and not post.author.last_name %}
                <a href="{% url 'posts:profile' username=post.author.username %}">
                  {{ post.author.username }}</a>
                           {% else %}
                <a href="{% url 'posts:profile' username=post.author.username %}">
                            {{ post.author.first_name }} {{ post.author.last_name }}</a>
                           {% endif %}
              </li>
              <li>
                    Дата публикации: {{ post.pub_date|date:"d F Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            <p>
              {{ post.text }}
            </p>
            <a href="{% if post.group.slug %}{% url 'posts:group_list' post.group.slug%}{% else %} / {% endif %}">Все записи группы</a>
          </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
     {% include 'posts/includes/paginator.html' %}
    </div>
  </main>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }} {% endblock title %}
{% load thumbnail %}
{% block content %}
  <main>
    <div class="container py-5">
      <h1>{{ group.title }}</h1>
      <p>
          {{ group.description }}
      </p>
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.first_name }} {{ post.author.last_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d F Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
        </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
  </main>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock title %}
{% load thumbnail %}
{% load cache %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <main> 
    <div class="container py-5">
      <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                    Автор: {% if not post.author.first_name and not post.author.last_name %}
                <a href="{% url 'posts:profile' username=post.author.username %}">
                  {{ post.author.username }}</a>
                           {% else %}
                <a href="{% url 'posts:profile' username=post.author.username %}">
                            {{ post.author.first_name }} {{ post.author.last_name }}</a>
                           {% endif %}
              </li>
              <li>
                    Дата публикации: {{ post.pub_date|date:"d F Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            <p>
              {{ post.text }}
            </p>
            <a href="{% if post.group.slug %}{% url 'posts:group_list' post.group.slug%}{% else %} / {% endif %}">Все записи группы</a>
          </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
     {% include 'posts/includes/paginator.html' %}
    </div>  
  </main>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock title %}
{% load thumbnail %}
{% load user_filters %}
{% block content %}
  <main>
    <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d F Y" }}
            </li>
            {% if post.group %}
                <li class="list-group-item">
                  Группа: {{ post.group.title }}
                  <a href="{% if post.group.slug %}{% url 'posts:group_list' post.group.slug%}{% else %} / {% endif %}">Все записи группы</a>
                </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.first_name }} {{ post.author.last_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="">
                Все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
          <p>
           {{ post.text }}
          </p>
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %}
        </article>
      </div>

  </main>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.first_name }} {{ author.last_name }}{% endblock title %}
{% load thumbnail %}
{% block content %}
  <main>
    <div class="container py-5 mb-5">
        <h1>Все посты пользователя {{ author.first_name }} {{ author.last_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }}</h3>
        {% if request.user.is_authenticated and request.user != author %}
         {% if following %}
            <a
              class="btn btn-lg btn-danger"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
         {% else %}
            <a
                    class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
           {% endif %}
        {% endif %}
        {% for post in page_obj %}
            <article>
              <ul>
                <li>
                  Автор: {{ author.first_name }} {{ author.last_name }}
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d F Y" }}
                </li>
              </ul>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              <p>
                {{ post.text }}
              </p>
              <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
              {% if post.author == request.user %}<a href="{% url 'posts:post_edit' post.id %}">Редактировать</a>{% endif %}
            </article>
            <a href="{% if post.group.slug %}{% url 'posts:group_list' post.group.slug%}{% else %} / {% endif %}">Все записи группы</a>
        {% endfor %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
        {% include 'posts/includes/paginator.html' %}
      </div>
  </main>
{% endblock content %}